import { createClient } from '@/utils/supabase/server'

export default async function FmeaPrintPage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params
  const supabase = await createClient()

  // Fetch Project Info
  const { data: project } = await supabase.from('projects').select('*').eq('id', id).single()

  // Fetch FMEA Data
  const { data: steps } = await supabase
    .from('process_steps')
    .select('*, pfmea_records(*)')
    .eq('project_id', id)
    .order('step_number', { ascending: true })

  return (
    <div className="min-h-screen bg-white text-black p-4 print-container">
      {/* 1. AIAG Standard Header */}
      <div className="border-2 border-black mb-4">
        <div className="grid grid-cols-4 divide-x-2 divide-black border-b-2 border-black">
          <div className="col-span-1 p-2 font-bold text-xl flex items-center justify-center bg-gray-100">
            FMEA
          </div>
          <div className="col-span-3 p-2">
            <div className="grid grid-cols-2 gap-4 text-xs">
              <div><span className="font-bold">Project:</span> {project.name}</div>
              <div><span className="font-bold">Part Number:</span> {project.part_number}</div>
              <div><span className="font-bold">Customer:</span> {project.customer}</div>
              <div><span className="font-bold">Date:</span> {new Date().toLocaleDateString()}</div>
            </div>
          </div>
        </div>
      </div>

      {/* 2. The Data Table */}
      <table className="w-full border-collapse border border-black text-xs">
        <thead>
          <tr className="bg-gray-200 text-center">
            <th className="border border-black p-1">Op No.</th>
            <th className="border border-black p-1">Process Step</th>
            <th className="border border-black p-1">Failure Mode</th>
            <th className="border border-black p-1">Effect</th>
            <th className="border border-black p-1 w-8">S</th>
            <th className="border border-black p-1">Cause</th>
            <th className="border border-black p-1 w-8">O</th>
            <th className="border border-black p-1">Current Control</th>
            <th className="border border-black p-1 w-8">D</th>
            <th className="border border-black p-1 w-8 bg-gray-300">RPN</th>
          </tr>
        </thead>
        <tbody>
          {steps?.map((step) => {
             // If a step has no risks, show one row with empty risk cells
             const rows = step.pfmea_records.length > 0 ? step.pfmea_records : [{}];
             
             return rows.map((risk: any, index: number) => (
               <tr key={risk.id || index}>
                 {/* Only show Step info on the first row of the group */}
                 {index === 0 && (
                   <>
                     <td className="border border-black p-1 text-center font-bold" rowSpan={rows.length}>
                       {step.step_number}
                     </td>
                     <td className="border border-black p-1" rowSpan={rows.length}>
                       {step.description}
                     </td>
                   </>
                 )}
                 <td className="border border-black p-1">{risk.failure_mode || '-'}</td>
                 <td className="border border-black p-1">{risk.failure_effect || '-'}</td>
                 <td className="border border-black p-1 text-center">{risk.severity || ''}</td>
                 <td className="border border-black p-1">{risk.cause || '-'}</td>
                 <td className="border border-black p-1 text-center">{risk.occurrence || ''}</td>
                 <td className="border border-black p-1">{risk.current_controls || '-'}</td>
                 <td className="border border-black p-1 text-center">{risk.detection || ''}</td>
                 <td className="border border-black p-1 text-center font-bold bg-gray-100">{risk.rpn || ''}</td>
               </tr>
             ));
          })}
        </tbody>
      </table>

      {/* 3. Auto-Print Script */}
      <PrintTrigger />
      
      {/* Footer Info */}
      <div className="mt-8 text-[10px] text-gray-500 text-center">
        Generated by APQP System • {new Date().getFullYear()} • Confidential
      </div>
    </div>
  )
}

// Small client component to trigger the browser print dialog
function PrintTrigger() {
  return (
    <script
      dangerouslySetInnerHTML={{
        __html: `window.onload = function() { window.print(); }`,
      }}
    />
  )
}
